export const FETCH_CARI_REQUEST = 'FETCH_CARI_REQUEST'
export const FETCH_CARI_SUCCESS = 'FETCH_CARI_SUCCESS'
export const FETCH_CARI_FAILURE = 'FETCH_CARI_FAILURE'

export const CREATE_CARI_REQUEST = 'CREATE_CARI_REQUEST'
export const CREATE_CARI_SUCCESS = 'CREATE_CARI_SUCCESS'
export const CREATE_CARI_FAILURE = 'CREATE_CARI_FAILURE'

export const UPDATE_CARI_REQUEST = 'UPDATE_CARI_REQUEST'
export const UPDATE_CARI_SUCCESS = 'UPDATE_CARI_SUCCESS'
export const UPDATE_CARI_FAILURE = 'UPDATE_CARI_FAILURE'

export const DELETE_CARI_REQUEST = 'DELETE_CARI_REQUEST'
export const DELETE_CARI_SUCCESS = 'DELETE_CARI_SUCCESS'
export const DELETE_CARI_FAILURE = 'DELETE_CARI_FAILURE'
